version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    environment:
      TZ: UTC
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
        API_PORT: $API_PORT
        AWS_ACCESS_KEY_ID:     $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        DB_HOST:               $DB_HOST
        DB_NAME:               $DB_NAME
        DB_USERNAME:           $DB_USERNAME
        DB_PASSWORD:           $DB_PASSWORD
        RAILS_MASTER_KEY:      $RAILS_MASTER_KEY
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "https://test-of-bike-front.herokuapp.com/"
    volumes:
      - ./api:/$WORKDIR
      - api-bundle:/usr/local/bundle:cached
    depends_on:
      - db
    ports:
      - "$API_PORT:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        API_URL: "https://test-of-bike-api.herokuapp.com/"
        FRONT_URL: $FRONT_PORT
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api
      
volumes:
  db-data:
  api-bundle: